// Do not alter this file, instead it should be generated by using `yarn svg`
// This will override this file and update the exported enum for use in the SvgIcon component

export enum TLASvg {
    arrowRight = 'arrowRight',
    burgerClose = 'burgerClose',
    burgerIcon = 'burgerIcon',
    checked = 'checked',
    chevronCircleRight = 'chevronCircleRight',
    chevronRight = 'chevronRight',
    circlePlusInverted = 'circlePlusInverted',
    circlePlus = 'circlePlus',
    errorTextIcon = 'errorTextIcon',
    eyeClosed = 'eyeClosed',
    eyeOpen = 'eyeOpen',
    searchIcon = 'searchIcon',
    signIn = 'signIn',
    signOut = 'signOut',
    successMessage = 'successMessage',
}