import Head from "next/head";
import styled from "styled-components";
import { mq } from "../../util/media-queries";
import PageTransition from "../pageTransition/pageTransition";
import { useNavStore } from "~/store/store";
import { ReactNode } from "react";

type Layout = {
    children: ReactNode;
};

const Layout = ({ children }: Layout) => {
    const { showNav } = useNavStore((state) => ({
        showNav: state.showNav,
    }));
    return (
        <>
            <Head>
                <title>Impact beer app</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DashboardWrapper>{children}</DashboardWrapper>
        </>
    );
};
export default Layout;

export const DashboardWrapper = styled.div(({}) => ({
    display: "flex",
    width: "100%",

    flexDirection: "column",
    [mq("lg")]: {
        flexDirection: "row",
        height: "100vh",
    },
}));
