// Do not alter this file, instead it should be generated by using `yarn svg`
// This will override this file and update the exported map for use in the SvgIcon component

import { FC } from "react";
import ArrowRight from "./arrow-right.svg";
import BurgerClose from "./burger-close.svg";
import BurgerIcon from "./burger-icon.svg";
import CalendarEmpty from "./calendar-empty.svg";
import Checked from "./checked.svg";
import ChevronCircleRight from "./chevron-circle-right.svg";
import ChevronRight from "./chevron-right.svg";
import CirclePlusInverted from "./circle-plus-inverted.svg";
import CirclePlus from "./circle-plus.svg";
import Email from "./email.svg";
import ErrorTextIcon from "./error-text-icon.svg";
import EyeClosed from "./eye-closed.svg";
import EyeOpen from "./eye-open.svg";
import Home from "./home.svg";
import Location from "./location.svg";
import LogOut from "./log-out.svg";
import People from "./people.svg";
import Phone from "./phone.svg";
import ProfileEdit from "./profile-edit.svg";
import Projects from "./projects.svg";
import SearchIcon from "./search-icon.svg";
import Search from "./search.svg";
import SignIn from "./sign-in.svg";
import SignOut from "./sign-out.svg";
import SliderArrowRight from "./slider-arrow-right.svg";
import SuccessMessage from "./success-message.svg";

export const TLAIcons: { [key: string]: FC<any> } = {
    arrowRight: ArrowRight,
    burgerClose: BurgerClose,
    burgerIcon: BurgerIcon,
    calendarEmpty: CalendarEmpty,
    checked: Checked,
    chevronCircleRight: ChevronCircleRight,
    chevronRight: ChevronRight,
    circlePlusInverted: CirclePlusInverted,
    circlePlus: CirclePlus,
    email: Email,
    errorTextIcon: ErrorTextIcon,
    eyeClosed: EyeClosed,
    eyeOpen: EyeOpen,
    home: Home,
    location: Location,
    logOut: LogOut,
    people: People,
    phone: Phone,
    profileEdit: ProfileEdit,
    projects: Projects,
    searchIcon: SearchIcon,
    search: Search,
    signIn: SignIn,
    signOut: SignOut,
    sliderArrowRight: SliderArrowRight,
    successMessage: SuccessMessage,
};
