// Do not alter this file, instead it should be generated by using `yarn svg`
// This will override this file and update the exported map for use in the SvgIcon component

import { FC } from 'react';
import ArrowRight from './arrow-right.svg';
import BurgerClose from './burger-close.svg';
import BurgerIcon from './burger-icon.svg';
import CalendarEmpty from './calendar-empty.svg';
import Checked from './checked.svg';
import ChevronCircleRight from './chevron-circle-right.svg';
import ChevronRight from './chevron-right.svg';
import CirclePlusInverted from './circle-plus-inverted.svg';
import CirclePlus from './circle-plus.svg';
import ErrorTextIcon from './error-text-icon.svg';
import EyeClosed from './eye-closed.svg';
import EyeOpen from './eye-open.svg';
import Location from './location.svg';
import LogOut from './log-out.svg';
import ProfileEdit from './profile-edit.svg';
import SearchIcon from './search-icon.svg';
import Search from './search.svg';
import SignIn from './sign-in.svg';
import SignOut from './sign-out.svg';
import SliderArrowRight from './slider-arrow-right.svg';
import SuccessMessage from './success-message.svg';

export const TLAIcons: { [key: string]: FC<any> } = {
    arrowRight: ArrowRight,
    burgerClose: BurgerClose,
    burgerIcon: BurgerIcon,
    calendarEmpty: CalendarEmpty,
    checked: Checked,
    chevronCircleRight: ChevronCircleRight,
    chevronRight: ChevronRight,
    circlePlusInverted: CirclePlusInverted,
    circlePlus: CirclePlus,
    errorTextIcon: ErrorTextIcon,
    eyeClosed: EyeClosed,
    eyeOpen: EyeOpen,
    location: Location,
    logOut: LogOut,
    profileEdit: ProfileEdit,
    searchIcon: SearchIcon,
    search: Search,
    signIn: SignIn,
    signOut: SignOut,
    sliderArrowRight: SliderArrowRight,
    successMessage: SuccessMessage,
}